SELECT NOMBRE FROM CLIENTE
INNER JOIN INSCRIPCION ON CLIENTE.ID = INSCRIPCION.ID_CLIENTE
WHERE EXISTS (
    SELECT 1
    FROM VISITAN
    INNER JOIN DISPONIBILIDAD
    ON VISITAN.ID_SUCURSAL = DISPONIBILIDAD.ID_SUCURSAL
    WHERE VISITAN.ID_CLIENTE = CLIENTE.ID
)